-- AlterTable
ALTER TABLE "Restaurant" ALTER COLUMN "lat" DROP NOT NULL,
ALTER COLUMN "long" DROP NOT NULL;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "lat" DROP NOT NULL,
ALTER COLUMN "long" DROP NOT NULL;
